### ISSUE TITLE
Bug: imdb engine

### ISSUE THREAD

**Issue by fleurc** [paulgoio/searxng#14]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 1.0.0

**Technical report**

Error
  * Error: KeyError
  * Percentage: 65
  * Parameters: `()`
  * File name: `searx/engines/imdb.py:60`
  * Function: `response`
  * Code: `for entry in suggestions['d']:`

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 15
  * Parameters: `('400', 'Bad Request', 'v2.sg.media-imdb.com')`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @fleurc ,
Thank you for your second bug report! Is IMDB getting blocked a lot for you? Looking at the error rate its only 15%... And checking: https://paulgo.io/search?q=%21imdb%20time&language=en-US&time_range=None&safesearch=1&categories=none works correctly for me. If this only happens sometimes I would like to close the issue, since the API still works correctly and getting sometimes blocked is normal.

**Comment by fleurc** [comment]
Sure, it was happening pretty often, but not exactly bothering me too much, i'll try to find a specific query to see if it breaks consistently

**Comment by fleurc** [comment]
That seems to be a pretty consistent behavior on some queries. If i search Spiderman Homecoming for an example it doesn't give any parsing error.

**Comment by dalf** [comment]
See https://github.com/searxng/searxng/pull/588 : the error appears when there is no result.

**Comment by mrpaulblack** [comment]
Woow that was fast. Thank you @dalf

**Comment by mrpaulblack** [comment]
Fixed in 5459ba20bd0155237812343bd071470d8e8359ff and https://github.com/searxng/searxng/commit/24c7d6300e4765be046b4e2bb1fde6d280ba049e upstream; Closing.
