### ISSUE TITLE
Bug: etools engine

### ISSUE THREAD

**Issue by zqpvr** [paulgoio/searxng#15]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/dalf/searxng
Branch: main
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @zqpvr ,
Thanks for your first issue! :D
After doing some testing: The engine works on my local computer and since it returns a 403 Forbidden HTTP status code, it makes me believe that my public instance is just getting blocked, because to many requests are coming from the one single IP.

There is not much I can do about this (maybe using a proxy, but I don't want to scale my instance up like this rn..)

Do you use the engine a lot? Otherwise I would like to close the issue...

**Comment by zqpvr** [comment]
You can close it.

**Comment by zqpvr** [comment]
You can close it.
