### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by fleurc** [paulgoio/searxng#19]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 70
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 5
  * Parameters: `('CAPTCHA',)`
  * File name: `searx/engines/startpage.py:66`
  * Function: `raise_captcha`
  * Code: `raise SearxEngineCaptchaException(suspended_time=7 * 24 * 3600)`

**Comment by mrpaulblack** [comment]
Hi @fleurc ,
Thanks for the PR; Startpage changed their API recently and they now block instances with a lot of requests with captchas: https://github.com/searxng/searxng/issues/692 . I cannot really do anything about this , well maybe proxies. But since startpage is just a proxy for the working google engine, I dont really see the point; Closing.
