### ISSUE TITLE
Possible to use Morty with PaulGo?

### ISSUE THREAD

**Issue by silverwings15** [paulgoio/searxng#23]
Hi, thanks for your amazing Searxng instance that i recently discovered. Apparently Morty proxy is integrated into Searx by default, but i don't see the proxy button on PaulGo search results, so i'm wondering if it's possible to be used, and if not, whether Morty can be integrated into your instance?

**Comment by mrpaulblack** [comment]
Hi @silverwings15 ,
Thank you for opening the issue. I used morty in the past on PaulGO but since the image_proxy got reworked upstream in SearXNG I am using the builtin /image_proxy in SearXNG. Its simpler and also still gets maintained in SearXNG. There is a ongoing effort upstream in SearXNG to fully remove morty from the stack and therefor also the proxy button.

If the proxy button a feature that is really important to you? Maybe as a compromise it could be a link to a privacy focused proxy instead of using morty. (Also morty proxy added a lot of requests to my instance); What do you think?

**Comment by silverwings15** [comment]
> There is a ongoing effort upstream in SearXNG to fully remove morty from the stack and therefor also the proxy button.

ah i wasn't aware of this, this is maybe SearXNG's first major divergence from Searx that i've seen. is it because morty is not in very active development? the proxy feature (doesn't have to be morty) would be a nice to have but definitely not essential, so please don't sweat it.

**Comment by mrpaulblack** [comment]
Actually there are a lot more big differences between SearXNG and searx: see readme with changelog: https://github.com/searxng/searxng ...

I opened a issue upstream about the proxy feature: https://github.com/searxng/searxng/issues/857

Also we want to simplify the stack and instead of using all those different pieces of software that are not very active in development, we rather use builtin tools. They make maintenance easier.

**Comment by silverwings15** [comment]
indeed there are more significant changes than i thought. i also totally agree with the rationale for streamlining the codebase. will keep an eye on the issue you filed and see how it goes, thanks again
