### ISSUE TITLE
Bug: qwant engine when search is 'daylight savings uk'

### ISSUE THREAD

**Issue by lumenav** [paulgoio/searxng#29]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 2022.03.05-740e3bc9

**How did you install SearXNG?**
 executing the searx/webapp.py file
**What happened?**

typed search of 'daylight savings uk'

Some results were returned but this error was shown on the right hand side of the display

**How To Reproduce**

Performing the same search I'd expect

**Expected behavior**

Results returned but no error
![Screenshot 2022-03-11 at 15 39 29](https://user-images.githubusercontent.com/101415086/157899317-3bb75a6c-ffac-442e-9c78-b80a170cb4cc.png)

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'api.qwant.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: searx.exceptions.SearxEngineAPIException
  * Percentage: 0
  * Parameters: `('API error::unknown',)`
  * File name: `searx/engines/qwant.py:123`
  * Function: `response`
  * Code: `raise SearxEngineAPIException('API error::' + msg)`

**Comment by mrpaulblack** [comment]
Hi @lumenav ,
This is because Qwant is sometimes blocking my IP for a day or so because of to many requests from my instance to their server. There are a lot of those issues already in this repo you can see another one here: https://github.com/paulgoio/searxng/issues/24 .

The only real way to fix this is to use a proxy with multiple public IP addresses... I will keep this open to track my progress on this, but this will take some time (could be multiple weeks). Keep in mind that this error does not do anything... The results still work as good as before (just without qwant sometimes)...

**Comment by mrpaulblack** [comment]
After a long time I finally set up a set of http proxy server; Since the search traffic to engines is not split between multiple public IPs, my instance should not get IP blocked for the foreseeable future :tada: ; Closing.
