### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by ghost** [paulgoio/searxng#3]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/paulgoio/searxng
Branch: main
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:97`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by MrPaulBlack** [comment]
Hi @Boranity ,
Thank you for your bug report. This bug happens because there is a lot of traffic from the single IP of my VPS server (where the SearXNG instance is running), that is going to google's servers. Google just blocks the IP of my server after some time, when too many requests happened.
I am looking into how I can fix the problem, but do not expect a fix in the near future tho...
