### ISSUE TITLE
Automated Docker image builds 

### ISSUE THREAD

**Issue by extremelyonline** [paulgoio/searxng#52]
Hello, may I please ask if you may be interested/have time to set up automated builds/push to Docker Hub/GitHub Packages? Thank you so much.

**Comment by mrpaulblack** [comment]
Hi,
I do have a gitlab ci that automatically pushes builds to dockerhub commits to the projects main branch. I do not want to automatically push to the production tag that is used on my instance, but I can do a different tag like testing and auto push to that docker tag when there is a change upstream in SearXNG... -> see: https://paulgo.dev/infra/paulgoio/searxng/-/pipelines


I will add this to the backlog for my instance and will work on this in the coming months. For now, I will keep pushes to the production and staging tag manually tho, so I can make sure that the build is working manually before deploying it...

**Comment by mrpaulblack** [comment]
No worries at all; I think this is a really good idea :+1:

**Comment by mrpaulblack** [comment]
Hi,
FYI I just setup a pipeline with renovate on my gitlab instance that automatically builds and pushes the `staging` tag each morning, if there are changes upstream. I am still approving the `production` tag manually, since I want to manually test changes before pushing them to my actual instance.
