### ISSUE TITLE
Omnibar search often fails

### ISSUE THREAD

**Issue by paul1149** [paulgoio/searxng#59]
Hi,

I'm very pleased with PaulGo, thank you for a great service. 

But sometimes searches from the Vivaldi address bar come up with a blank search input page.

I use the POST method for on-site searches. 

My search string in Vivaldi is `https://paulgo.io/search?q=%s&language=en-US&time_range=&safesearch=1&categories=general`, where it is **not** a POST search.

It's frustrating, and often I will copy the search string to clipboard in case it is lost to a failed search attempt.

Thanks.

**Comment by mrpaulblack** [comment]
Yeah, I noticed that too. My guess it's because of how I handle IPv6 addresses. Basically my server supports IPv6, but I did not configure IPv6 in docker. So all IPv6 requests are translated to a single IPv4 address from the view of my SearXNG instance.
From there the SearXNG limiter (which blocks bot requests) is handling some searches as suspicious and redirect them to the search input field instead of returning the actual result page.
I am currently in the process to moving to a new VPS at OVH from my current one, and I will also set up IPv6 properly this time.
Will write on this ticket, once I resolved the issue, thanks for the bug report :+1:

**Comment by paul1149** [comment]
Interesting. I'm not knowingly sending IPv6, but who knows? You certainly know more about this than I.

Great site, and thanks for looking into this.

**Comment by mrpaulblack** [comment]
Hi,
I moved my instance to a new VPS server. This new server can handle IPv6 correctly. You can check for yourself; If you have a IPv6 address you will see it here now: https://paulgo.io/search?q=what%20is%20my%20ip&language=en-US&time_range=&safesearch=1&categories=general

Because of that those annoying redirects to the start page should not happen as often anymore. I will close the issue for now, but if this happens again for you, please leave a comment :+1: ; Closing.

**Comment by paul1149** [comment]
Excellent. Since your post, I have not had one instance of failure. Seems like you nailed both the problem and the solution. Good work!

**Comment by paul1149** [comment]
For some reason it's begun happening again. A few times in the last two days.

**Comment by mrpaulblack** [comment]
Yeah, I noticed it too :/

I will look into it...

**Comment by mrpaulblack** [comment]
Hi,
For me, it's not happening a lot anymore. I checked out different options, but in the end the ocational redirect is IMO ok for the bot protection; Closing.

More about this topic:
* https://github.com/searxng/searxng/issues/3191
* https://github.com/searxng/searxng/pull/2357/files/80af38d37b21dc6e5edbf27bd22310db42a6f923#diff-437a93b109d23719837e77f803998a188751dcc7f60cf711996939653defa967
