### ISSUE TITLE
Suspended: unexpected crash

### ISSUE THREAD

**Issue by Cheesealicious** [paulgoio/searxng#61]
Howdy! 
I've been using your instance for a couple months now, but for some reason every couple of searches, like about 1 in 3 searches, end up with no search results and an error message that reads "no results" and "suspended: unexpected crash" (see image below). Sometimes it's bing that has the error message next to it, sometimes it's google. The numbers next to the blue bars range anywhere from 1 to 6.

I'm not very tech savvy, so please let me know if you need me to grab any additional information.

Thanks!
Cheese
![Screenshot_20240929-001713_Firefox](https://github.com/user-attachments/assets/fa30b912-6ce6-41e3-a878-57d420d8a346)

**Comment by mrpaulblack** [comment]
Hi,
Sadly my instance is currently under heavy attack with more than 1 million requests per day. Normally I have more like 200.000 requests per day. Because of this I am blocked by upstream engines and since I am not logging IP addresses I cannot really do anything about it :/

**Comment by mrpaulblack** [comment]
Actually they just stopped so for now it should be better.

**Comment by Cheesealicious** [comment]
Hi, quick question, what do you mean by under attack? The error messages started back up again last night.

**Comment by mrpaulblack** [comment]
Hmm I think someone is targetting my instance with automated requests. I get a lot of requests at specific times that also stop again at specific times. Like 800 requests per minute for exactly one hour and then the requests stop again.

Since the bot protection does not seem to block those requests, google starts blocking my instance at some point in time.

Only thing I can really do is try to block those automated requests, but sine I am not logging I don't even know how to block them. Or I could buy more IP addresses to disperse the load between those IPs (so google does not block my instance anymore). But I need to pay for those IPs every month I am currently already using 5 IPv4 addresses and a IPv6 network. Basically I don't want to pay for more addresses.

Currently, I am waiting and hoping that eventually they will leave my instance alone.

**Comment by mrpaulblack** [comment]
Responses seem to currently not be blocked anymore by google and bing. Will close the ticket for now :+1:
